nombre = input("Ingrese su nombre: ")
apellido = input("Ingrese su apellido: ")
rut = input("Ingrese su Rut: ")
correo_duoc = input("Ingrese su correo de Duoc: ")
sede_duoc = input("Ingrese su sede de Duoc: ")

print("Nombre:", nombre)
print("Apellido:", apellido)
print("Rut:", rut)
print("Correo Duoc:", correo_duoc)
print("Sede Duoc:", sede_duoc)
